categories:
  - title: ':rocket: Features'
    labels:
      - 'feature'
  - title: ':beetle: Bug Fixes'
    labels:
      - 'hotfix'
      - 'bugfix'
      - 'invalid'
  - title: ':construction_worker: Maintenance'
    label: 
      - 'infra'
  - title: ':books: Documentation'
    label: 
      - 'docs'
      - 'question'
  - title: ':books: Analysis'
    label: 
      - 'analysis'
      - 'best practice'

template: |
  ## What’s Changed
  $CHANGES
