# Base path to WoW directory
server: Grobbulus
server_id: 69

roles:
  - name: Amazona
    account: 396255466#1
    role: ahm
  - name: Amazoni
    account: BLUEM
    role: mule
  - name: Quicksa
    account: BLUEM
    role: mule
