location_info:
  '0': Inventory
  '2': Bank
  '5': Mailbox
  '10': Auctions
auction_type_labels:
  completedAuctions: "sell_price"
  completedBidsBuyouts: "buy_price"
  failedAuctions: "failed"
flask_settings:
  CUSTOM_STATIC_PATH: 'data'