# Items is the central place to designate any item of interest
# Adding an item as a key will ensure that item is included in filtering
# backup_price is used for items that do not usually appear in AH (poisons, vials)
# full_deposit (48h for single item) indicates if it's a sellable item
# made_from is the recipe for the item including vials. Referenced items must be included in this doc

Arcane Crystal:
  ideal_holding: 6
  max_holding: 18
  full_deposit: 1200
  group: Buy
Arcanite Bar:
  ideal_holding: 6
  max_holding: 12
  group: Sell
Thorium Bar:
  group: Other

Black Lotus:
  group: Buy # Set to sell so that it doesnt appear in snatch list

# 1255 potions, 251 stacks
# Roughly 304 stacks of materials
Flask of the Titans:
  full_deposit: 500 #check
  group: Sell
  made_from:
    Gromsblood: 30
    Stonescale Eel: 10
    Black Lotus: 1
    Crystal Vial: 1 
  ideal_holding: 5
Elixir of Fortitude:
  full_deposit: 60 
  group: Sell
  made_from:
    Goldthorn: 1
    Leaded Vial: 1
    Wild Steelbloom: 1 
  ideal_holding: 100
Elixir of Giants:
  full_deposit: 420 
  group: Sell
  made_from:
    Crystal Vial: 1
    Gromsblood: 1
    Sungrass: 1 
  ideal_holding: 125
Elixir of Greater Agility:
  full_deposit: 360 
  group: Sell
  made_from:
    Crystal Vial: 1
    Goldthorn: 1
    Sungrass: 1
  ideal_holding: 100
Elixir of Superior Defense:
  full_deposit: 300
  group: Sell
  made_from:
    Crystal Vial: 1
    Leaded Vial: 2
    Stonescale Eel: 2
    Sungrass: 1 
  ideal_holding: 100
Elixir of the Mongoose:
  full_deposit: 744
  group: Sell
  made_from:
    Crystal Vial: 1
    Mountain Silversage: 2
    Plaguebloom: 2   
  ideal_holding: 100
Free Action Potion:
  full_deposit: 36
  group: Sell
  made_from:
    Empty Vial: 2
    Leaded Vial: 1
    Oily Blackmouth: 4
    Stranglekelp: 1 
  ideal_holding: 125
Greater Arcane Protection Potion:
  full_deposit: 444
  group: Sell
  made_from:
    Crystal Vial: 1
    Dream Dust: 1
    Dreamfoil: 1 
  ideal_holding: 50
Greater Stoneshield Potion:
  full_deposit: 444
  group: Sell
  made_from:
    Crystal Vial: 1
    Leaded Vial: 3
    Stonescale Eel: 3
    Thorium Ore: 1 
  ideal_holding: 50
Invisibility Potion:
  full_deposit: 300
  group: Sell
  made_from:
    Crystal Vial: 1
    Ghost Mushroom: 1
    Sungrass: 1 
  ideal_holding: 100
Limited Invulnerability Potion:
  full_deposit: 12
  group: Sell
  made_from:
    Blindweed: 2
    Crystal Vial: 1
    Ghost Mushroom: 1 
  ideal_holding: 100
Mighty Rage Potion:
  full_deposit: 300
  group: Sell
  made_from:
    Crystal Vial: 1
    Gromsblood: 3  
  ideal_holding: 100
Swiftness Potion:
  full_deposit: 12
  group: Sell
  made_from:
    Briarthorn: 1
    Empty Vial: 1
    Swiftthistle: 1 
  ideal_holding: 100

Blackmouth Oil:
  full_deposit: 100
  group: Other
  made_from:
    Empty Vial: 1
    Oily Blackmouth: 2
Fire Oil:
  full_deposit: null
  group: Other
  made_from:
    Empty Vial: 1
    Firefin Snapper: 2
Stonescale Oil:
  full_deposit: null
  group: Other
  made_from:
    Leaded Vial: 1
    Stonescale Eel: 1

Oily Blackmouth:
  group: Buy 
Stonescale Eel:
  group: Buy

Blindweed:
  group: Buy
Briarthorn:
  group: Buy  
Dream Dust:
  group: Buy
Dreamfoil:
  group: Buy
Swiftthistle:
  group: Buy
Ghost Mushroom:
  group: Buy
Goldthorn:
  group: Buy
Gromsblood:
  group: Buy
Mountain Silversage:
  group: Buy
Plaguebloom:
  group: Buy
Stranglekelp:
  group: Buy
Sungrass:
  group: Buy
Thorium Ore:
  group: Buy
Wild Steelbloom:
  group: Buy

Crystal Vial:
  backup_price: 400
  group: Other
Leaded Vial:
  backup_price: 32
  group: Other
Empty Vial:
  backup_price: 3
  group: Other