# Items is the central place to designate any item of interest
# Adding an item as a key will ensure that item is included in filtering
# backup_price is used for items that do not usually appear in AH (poisons, vials)
# full_deposit (48h for single item) indicates if it's a sellable item
# made_from is the recipe for the item including vials. Referenced items must be included in this doc

Arcane Crystal:
  min_holding: 8
  max_holding: 20
  Buy: True
Arcanite Bar:
  min_holding: 4
  max_holding: 24
  Sell: True
  made_from:
    Arcane Crystal: 1
    TRANSMUTE_TIME: 1
Thorium Bar:
  min_holding: 8
  max_holding: 28
  Buy: True

Black Lotus:
  min_holding: 1
  max_holding: 10
  Buy: True

# 1255 potions, 251 stacks
# Roughly 304 stacks of materials
Flask of the Titans:
  min_holding: 2
  max_holding: 10
  Sell: True
  made_from:
    Gromsblood: 30
    Stonescale Eel: 10
    Black Lotus: 1
    Crystal Vial: 1 
Elixir of Fortitude:
  min_holding: 20
  max_holding: 100
  Sell: True
  made_from:
    Goldthorn: 1
    Leaded Vial: 1
    Wild Steelbloom: 1 
Elixir of Giants:
  min_holding: 20
  max_holding: 100  
  Sell: True
  made_from:
    Crystal Vial: 1
    Gromsblood: 1
    Sungrass: 1 
Elixir of Greater Agility:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Crystal Vial: 1
    Goldthorn: 1
    Sungrass: 1
Elixir of Superior Defense:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Crystal Vial: 1
    Leaded Vial: 2
    Stonescale Eel: 2
    Sungrass: 1 
Elixir of the Mongoose:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Crystal Vial: 1
    Mountain Silversage: 2
    Plaguebloom: 2   
Free Action Potion:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Empty Vial: 2
    Leaded Vial: 1
    Oily Blackmouth: 4
    Stranglekelp: 1 
Greater Stoneshield Potion:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Crystal Vial: 1
    Leaded Vial: 3
    Stonescale Eel: 3
    Thorium Ore: 1 
Invisibility Potion:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Crystal Vial: 1
    Ghost Mushroom: 1
    Sungrass: 1 
Limited Invulnerability Potion:
  min_holding: 20
  max_holding: 50
  Sell: True
  made_from:
    Blindweed: 2
    Crystal Vial: 1
    Ghost Mushroom: 1 
Mighty Rage Potion:
  min_holding: 20
  max_holding: 100
  Sell: True
  made_from:
    Crystal Vial: 1
    Gromsblood: 3  
Swiftness Potion:
  min_holding: 10
  max_holding: 30
  Sell: True
  made_from:
    Briarthorn: 1
    Empty Vial: 1
    Swiftthistle: 1 

Greater Arcane Protection Potion:
  min_holding: 5
  max_holding: 30
  Sell: True
  made_from:
    Crystal Vial: 1
    Dream Dust: 1
    Dreamfoil: 1 
Greater Nature Protection Potion:
  min_holding: 5
  max_holding: 40
  Sell: True
  made_from:
    Crystal Vial: 1
    Elemental Earth: 1
    Dreamfoil: 1
Greater Shadow Protection Potion:    
  min_holding: 5
  max_holding: 40
  Sell: True
  made_from:
    Crystal Vial: 1
    Shadow Oil: 1
    Dreamfoil: 1 

Blackmouth Oil:
  made_from:
    Empty Vial: 1
    Oily Blackmouth: 2
Stonescale Oil:
  made_from:
    Leaded Vial: 1
    Stonescale Eel: 1
Shadow Oil:
  made_from:
    Leaded Vial: 1
    Fadeleaf: 4
    Grave Moss: 4

Oily Blackmouth:
  max_holding: 100
  Buy: True 
Stonescale Eel:
  max_holding: 100
  Buy: True

Blindweed:
  max_holding: 100
  Buy: True
Briarthorn:
  max_holding: 100
  Buy: True  
Dream Dust:
  max_holding: 100
  Buy: True
Dreamfoil:
  max_holding: 100
  Buy: True
Swiftthistle:
  max_holding: 100
  Buy: True
Ghost Mushroom:
  max_holding: 100
  Buy: True
Goldthorn:
  max_holding: 100
  Buy: True
Gromsblood:
  max_holding: 100
  Buy: True
Mountain Silversage:
  max_holding: 100
  Buy: True
Plaguebloom:
  max_holding: 100
  Buy: True
Stranglekelp:
  max_holding: 100
  Buy: True
Sungrass:
  max_holding: 100
  Buy: True
Thorium Ore:
  max_holding: 100
  Buy: True
Wild Steelbloom:
  max_holding: 100
  Buy: True

Fadeleaf:
  max_holding: 60
  Buy: True
Grave Moss:
  max_holding: 60
  Buy: True
Elemental Earth:
  max_holding: 40
  Buy: True

# Gear for characters
Winterfall Firewater:
  max_holding: 20
  Buy: True
Elemental Sharpening Stone:
  max_holding: 20
  Buy: True
Major Healing Potion:
  max_holding: 40
  Buy: True
Heavy Runecloth Bandage:
  max_holding: 60
  made_from:
    Runecloth: 2
Runecloth:
  max_holding: 40
  Buy: True
Spider Sausage:
  max_holding: 80
  made_from:
    White Spider Meat: 2
White Spider Meat:
  max_holding: 40
  Buy: True
Dense Sharpening Stone:
  max_holding: 80
  Buy: True

Crystal Vial:
  vendor_price: 400
Leaded Vial:
  vendor_price: 32
Empty Vial:
  vendor_price: 3
TRANSMUTE_TIME:
  vendor_price: 100000