# Base path to WoW directory
warcraft_path: /Applications/World of Warcraft/_classic_/
auction_main: 
  name: Amazona
  realm: Grobbulus
  account: 396255466#1

accounts:
  - BLUEM
  - 396255466#1
  - 801032581#1