# Base path to WoW directory
warcraft_path: /Applications/World of Warcraft/_classic_/

server: Grobbulus
server_id: 69

roles:
  - name: Amazona
    account: 396255466#1
    role: ahm
  - name: Amazoni
    account: BLUEM
    role: mule
  - name: Quicksa
    account: BLUEM
    role: mule

accounts:
  - BLUEM
  - 396255466#1
  - 801032581#1

booty:
  CHROMEDRIVER_PATH: "/Users/nicholasjenkins/Documents/chromedriver"
  base: "https://www.bootybaygazette.com/#us/"
  api: "https://www.bootybaygazette.com/api/item.php?house="
  PAGE_WAIT: 1

analysis:
  USER_STD_SPREAD: 7
  ITEM_PRICE_OUTLIER_CAP: 0.025
  ROLLING_BUYOUT_SPAN: 100
  BB_MAT_PRICE_RATIO: 0.5
  MAX_LISTINGS_PROBABILITY: 500
