# Base path to WoW directory
warcraft_path: /Applications/World of Warcraft/_classic_/

roles:
  - name: Amazona
    account: 396255466#1
    role: ahm
  - name: Amazoni
    account: BLUEM
    role: mule
  - name: Quicksa
    account: BLUEM
    role: mule

accounts:
  - BLUEM
  - 396255466#1
  - 801032581#1

bb_selenium:
  CHROMEDRIVER_PATH: "/Users/nicholasjenkins/Documents/chromedriver"
  BB_BASEURL: "https://www.bootybaygazette.com/#us/grobbulus-a"
  BB_ITEMAPI: "https://www.bootybaygazette.com/api/item.php?house=69&item="
  PAGE_WAIT: 1
