name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - run: /opt/hostedtoolcache/Python/3.7.9/x64/bin/python -m pip install --upgrade pip==20.1.1                
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.0.10
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
